name: antarctic_ars_dataset
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ffmpeg
  - numpy=2.4.*
  - pandas<3.0
  - matplotlib=3.10.*
  - seaborn=0.13.*
  - xarray=2026.2.*
  - huggingface_hub=1.9.*
  - h5netcdf=1.8.*
  - h5py=3.16.*
  - pytables=3.11.*
  - pytest
  - fastparquet
  - pip:
    - dask=2026.3.*
    - ray==2.54.*
    - mystmd
    - cartopy=0.25.*
    - earthaccess==0.17.0
    - earthaccess[virtualizarr]
    - tqdm
    - jupyterlab_myst==2.6.*
    - jupyter-keepalive==0.3.*
    - -e . # used to install the editable version of artools while in development
