name: antarctic_ars_dataset
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - ipywidgets
  - pip
  - mystmd
  - ffmpeg
  - numpy
  - cartopy
  - pandas
  - matplotlib
  - seaborn
  - xarray
  - netcdf4
  - huggingface_hub
  - h5netcdf
  - h5py
  - pytables
  - dask
  - pip:
    - ray
    - earthaccess
    - tqdm
    - jupyterlab_myst
    - -e . # used to install the editable version of artools while in development