name: antarctic_ars_dataset
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ffmpeg
  - ipykernel
  - ipython
  - numpy=2.4.*
  - pandas=3.0.*
  - matplotlib=3.10.*
  - seaborn=0.13.*
  - xarray=2026.2.*
  - huggingface_hub=1.9.*
  - h5netcdf=1.8.*
  - h5py=3.16.*
  - pytables=3.11.*
  - pytest
  - pip:
    - dask==2026.3.*
    - ray==2.54.*
    - cartopy==0.25.*
    - earthaccess==0.16.0
    - tqdm
    - mystmd
    - jupyterlab_myst
    - jupyter-keepalive
